/*
 * Copyright 2016 Finn Bock
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.bckfnn.taggersty;

import java.util.function.Consumer;

/**
 * HtmlTags is the base class of html generators. All the methods for HTML tags are
 * generated by the main method.
 */
public class HtmlTags extends Tags {
    public static final String _class = "class";
    public final String $class = _class;

    public HtmlTags() {
        super(null);
    }

    public HtmlTags(TagsOutput output) {
        super(output);
    }

    public HtmlTags(TagsOutput output, Generator g) {
        super(output);
    }

    public static void run(TagsOutput output, Consumer<HtmlTags> g) {
        g.accept(new HtmlTags(output));
    }

    public void render() {
        throw new RuntimeException("must be overriden");
    }

    public void render(TagsOutput output) {
        output(output);
        render();
    }

    /**
     * Shortcut method for adding a id attribute.
     * @param value the id value.
     */
    public void id(String value) {
        attr("id", value);
    }


    /**
     * Generate a list of method for each html tag.
     * @param args command arguments, not used.
     */
    public static void main(String[] args) {
        Tags.generate(null, new String[] {
                "html", "head", "meta", "title", "script", "link",
                "body", "div", "h1", "h2", "h3", "h4", "h5",
                "ul", "li", "ol", "table", "tr", "th", "td", "col", "thead", "tbody", "tfoot",
                "form", "input", "select", "option", "textarea", "button",
                "label", "p", "i", "a", "span", "img", "br", "small", "strong",
        });
    }

    /**
     * Create en empty a @code{html} tag
     */
    public void html() {
        tag("html");
    }

    /**
     * Create en empty a @code{html} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void html(String attr, String value) {
        tag("html", attr, value);
    }

    /**
     * Create en empty a @code{html} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void html(String attr1, String value1, String attr2, String value2) {
        tag("html", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{html} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void html(Generator body) {
        tag("html", null, null, null, null, body);
    }

    /**
     * Create a @code{html} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void html(String attr, String value, Generator body) {
        tag("html", attr, value, null, null, body);
    }

    /**
     * Create a @code{html} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void html(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("html", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{head} tag
     */
    public void head() {
        tag("head");
    }

    /**
     * Create en empty a @code{head} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void head(String attr, String value) {
        tag("head", attr, value);
    }

    /**
     * Create en empty a @code{head} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void head(String attr1, String value1, String attr2, String value2) {
        tag("head", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{head} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void head(Generator body) {
        tag("head", null, null, null, null, body);
    }

    /**
     * Create a @code{head} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void head(String attr, String value, Generator body) {
        tag("head", attr, value, null, null, body);
    }

    /**
     * Create a @code{head} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void head(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("head", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{meta} tag
     */
    public void meta() {
        tag("meta");
    }

    /**
     * Create en empty a @code{meta} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void meta(String attr, String value) {
        tag("meta", attr, value);
    }

    /**
     * Create en empty a @code{meta} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void meta(String attr1, String value1, String attr2, String value2) {
        tag("meta", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{meta} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void meta(Generator body) {
        tag("meta", null, null, null, null, body);
    }

    /**
     * Create a @code{meta} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void meta(String attr, String value, Generator body) {
        tag("meta", attr, value, null, null, body);
    }

    /**
     * Create a @code{meta} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void meta(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("meta", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{title} tag
     */
    public void title() {
        tag("title");
    }

    /**
     * Create en empty a @code{title} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void title(String attr, String value) {
        tag("title", attr, value);
    }

    /**
     * Create en empty a @code{title} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void title(String attr1, String value1, String attr2, String value2) {
        tag("title", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{title} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void title(Generator body) {
        tag("title", null, null, null, null, body);
    }

    /**
     * Create a @code{title} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void title(String attr, String value, Generator body) {
        tag("title", attr, value, null, null, body);
    }

    /**
     * Create a @code{title} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void title(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("title", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{script} tag
     */
    public void script() {
        tag("script");
    }

    /**
     * Create en empty a @code{script} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void script(String attr, String value) {
        tag("script", attr, value);
    }

    /**
     * Create en empty a @code{script} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void script(String attr1, String value1, String attr2, String value2) {
        tag("script", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{script} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void script(Generator body) {
        tag("script", null, null, null, null, body);
    }

    /**
     * Create a @code{script} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void script(String attr, String value, Generator body) {
        tag("script", attr, value, null, null, body);
    }

    /**
     * Create a @code{script} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void script(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("script", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{link} tag
     */
    public void link() {
        tag("link");
    }

    /**
     * Create en empty a @code{link} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void link(String attr, String value) {
        tag("link", attr, value);
    }

    /**
     * Create en empty a @code{link} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void link(String attr1, String value1, String attr2, String value2) {
        tag("link", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{link} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void link(Generator body) {
        tag("link", null, null, null, null, body);
    }

    /**
     * Create a @code{link} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void link(String attr, String value, Generator body) {
        tag("link", attr, value, null, null, body);
    }

    /**
     * Create a @code{link} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void link(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("link", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{body} tag
     */
    public void body() {
        tag("body");
    }

    /**
     * Create en empty a @code{body} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void body(String attr, String value) {
        tag("body", attr, value);
    }

    /**
     * Create en empty a @code{body} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void body(String attr1, String value1, String attr2, String value2) {
        tag("body", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{body} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void body(Generator body) {
        tag("body", null, null, null, null, body);
    }

    /**
     * Create a @code{body} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void body(String attr, String value, Generator body) {
        tag("body", attr, value, null, null, body);
    }

    /**
     * Create a @code{body} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void body(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("body", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{div} tag
     */
    public void div() {
        tag("div");
    }

    /**
     * Create en empty a @code{div} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void div(String attr, String value) {
        tag("div", attr, value);
    }

    /**
     * Create en empty a @code{div} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void div(String attr1, String value1, String attr2, String value2) {
        tag("div", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{div} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void div(Generator body) {
        tag("div", null, null, null, null, body);
    }

    /**
     * Create a @code{div} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void div(String attr, String value, Generator body) {
        tag("div", attr, value, null, null, body);
    }

    /**
     * Create a @code{div} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void div(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("div", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{h1} tag
     */
    public void h1() {
        tag("h1");
    }

    /**
     * Create en empty a @code{h1} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void h1(String attr, String value) {
        tag("h1", attr, value);
    }

    /**
     * Create en empty a @code{h1} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void h1(String attr1, String value1, String attr2, String value2) {
        tag("h1", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{h1} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void h1(Generator body) {
        tag("h1", null, null, null, null, body);
    }

    /**
     * Create a @code{h1} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void h1(String attr, String value, Generator body) {
        tag("h1", attr, value, null, null, body);
    }

    /**
     * Create a @code{h1} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void h1(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("h1", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{h2} tag
     */
    public void h2() {
        tag("h2");
    }

    /**
     * Create en empty a @code{h2} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void h2(String attr, String value) {
        tag("h2", attr, value);
    }

    /**
     * Create en empty a @code{h2} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void h2(String attr1, String value1, String attr2, String value2) {
        tag("h2", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{h2} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void h2(Generator body) {
        tag("h2", null, null, null, null, body);
    }

    /**
     * Create a @code{h2} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void h2(String attr, String value, Generator body) {
        tag("h2", attr, value, null, null, body);
    }

    /**
     * Create a @code{h2} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void h2(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("h2", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{h3} tag
     */
    public void h3() {
        tag("h3");
    }

    /**
     * Create en empty a @code{h3} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void h3(String attr, String value) {
        tag("h3", attr, value);
    }

    /**
     * Create en empty a @code{h3} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void h3(String attr1, String value1, String attr2, String value2) {
        tag("h3", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{h3} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void h3(Generator body) {
        tag("h3", null, null, null, null, body);
    }

    /**
     * Create a @code{h3} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void h3(String attr, String value, Generator body) {
        tag("h3", attr, value, null, null, body);
    }

    /**
     * Create a @code{h3} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void h3(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("h3", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{h4} tag
     */
    public void h4() {
        tag("h4");
    }

    /**
     * Create en empty a @code{h4} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void h4(String attr, String value) {
        tag("h4", attr, value);
    }

    /**
     * Create en empty a @code{h4} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void h4(String attr1, String value1, String attr2, String value2) {
        tag("h4", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{h4} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void h4(Generator body) {
        tag("h4", null, null, null, null, body);
    }

    /**
     * Create a @code{h4} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void h4(String attr, String value, Generator body) {
        tag("h4", attr, value, null, null, body);
    }

    /**
     * Create a @code{h4} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void h4(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("h4", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{h5} tag
     */
    public void h5() {
        tag("h5");
    }

    /**
     * Create en empty a @code{h5} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void h5(String attr, String value) {
        tag("h5", attr, value);
    }

    /**
     * Create en empty a @code{h5} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void h5(String attr1, String value1, String attr2, String value2) {
        tag("h5", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{h5} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void h5(Generator body) {
        tag("h5", null, null, null, null, body);
    }

    /**
     * Create a @code{h5} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void h5(String attr, String value, Generator body) {
        tag("h5", attr, value, null, null, body);
    }

    /**
     * Create a @code{h5} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void h5(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("h5", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{ul} tag
     */
    public void ul() {
        tag("ul");
    }

    /**
     * Create en empty a @code{ul} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void ul(String attr, String value) {
        tag("ul", attr, value);
    }

    /**
     * Create en empty a @code{ul} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void ul(String attr1, String value1, String attr2, String value2) {
        tag("ul", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{ul} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void ul(Generator body) {
        tag("ul", null, null, null, null, body);
    }

    /**
     * Create a @code{ul} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void ul(String attr, String value, Generator body) {
        tag("ul", attr, value, null, null, body);
    }

    /**
     * Create a @code{ul} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void ul(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("ul", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{li} tag
     */
    public void li() {
        tag("li");
    }

    /**
     * Create en empty a @code{li} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void li(String attr, String value) {
        tag("li", attr, value);
    }

    /**
     * Create en empty a @code{li} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void li(String attr1, String value1, String attr2, String value2) {
        tag("li", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{li} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void li(Generator body) {
        tag("li", null, null, null, null, body);
    }

    /**
     * Create a @code{li} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void li(String attr, String value, Generator body) {
        tag("li", attr, value, null, null, body);
    }

    /**
     * Create a @code{li} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void li(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("li", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{ol} tag
     */
    public void ol() {
        tag("ol");
    }

    /**
     * Create en empty a @code{ol} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void ol(String attr, String value) {
        tag("ol", attr, value);
    }

    /**
     * Create en empty a @code{ol} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void ol(String attr1, String value1, String attr2, String value2) {
        tag("ol", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{ol} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void ol(Generator body) {
        tag("ol", null, null, null, null, body);
    }

    /**
     * Create a @code{ol} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void ol(String attr, String value, Generator body) {
        tag("ol", attr, value, null, null, body);
    }

    /**
     * Create a @code{ol} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void ol(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("ol", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{table} tag
     */
    public void table() {
        tag("table");
    }

    /**
     * Create en empty a @code{table} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void table(String attr, String value) {
        tag("table", attr, value);
    }

    /**
     * Create en empty a @code{table} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void table(String attr1, String value1, String attr2, String value2) {
        tag("table", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{table} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void table(Generator body) {
        tag("table", null, null, null, null, body);
    }

    /**
     * Create a @code{table} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void table(String attr, String value, Generator body) {
        tag("table", attr, value, null, null, body);
    }

    /**
     * Create a @code{table} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void table(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("table", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{tr} tag
     */
    public void tr() {
        tag("tr");
    }

    /**
     * Create en empty a @code{tr} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void tr(String attr, String value) {
        tag("tr", attr, value);
    }

    /**
     * Create en empty a @code{tr} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void tr(String attr1, String value1, String attr2, String value2) {
        tag("tr", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{tr} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void tr(Generator body) {
        tag("tr", null, null, null, null, body);
    }

    /**
     * Create a @code{tr} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void tr(String attr, String value, Generator body) {
        tag("tr", attr, value, null, null, body);
    }

    /**
     * Create a @code{tr} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void tr(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("tr", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{th} tag
     */
    public void th() {
        tag("th");
    }

    /**
     * Create en empty a @code{th} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void th(String attr, String value) {
        tag("th", attr, value);
    }

    /**
     * Create en empty a @code{th} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void th(String attr1, String value1, String attr2, String value2) {
        tag("th", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{th} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void th(Generator body) {
        tag("th", null, null, null, null, body);
    }

    /**
     * Create a @code{th} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void th(String attr, String value, Generator body) {
        tag("th", attr, value, null, null, body);
    }

    /**
     * Create a @code{th} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void th(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("th", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{td} tag
     */
    public void td() {
        tag("td");
    }

    /**
     * Create en empty a @code{td} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void td(String attr, String value) {
        tag("td", attr, value);
    }

    /**
     * Create en empty a @code{td} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void td(String attr1, String value1, String attr2, String value2) {
        tag("td", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{td} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void td(Generator body) {
        tag("td", null, null, null, null, body);
    }

    /**
     * Create a @code{td} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void td(String attr, String value, Generator body) {
        tag("td", attr, value, null, null, body);
    }

    /**
     * Create a @code{td} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void td(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("td", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{col} tag
     */
    public void col() {
        tag("col");
    }

    /**
     * Create en empty a @code{col} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void col(String attr, String value) {
        tag("col", attr, value);
    }

    /**
     * Create en empty a @code{col} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void col(String attr1, String value1, String attr2, String value2) {
        tag("col", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{col} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void col(Generator body) {
        tag("col", null, null, null, null, body);
    }

    /**
     * Create a @code{col} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void col(String attr, String value, Generator body) {
        tag("col", attr, value, null, null, body);
    }

    /**
     * Create a @code{col} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void col(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("col", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{thead} tag
     */
    public void thead() {
        tag("thead");
    }

    /**
     * Create en empty a @code{thead} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void thead(String attr, String value) {
        tag("thead", attr, value);
    }

    /**
     * Create en empty a @code{thead} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void thead(String attr1, String value1, String attr2, String value2) {
        tag("thead", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{thead} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void thead(Generator body) {
        tag("thead", null, null, null, null, body);
    }

    /**
     * Create a @code{thead} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void thead(String attr, String value, Generator body) {
        tag("thead", attr, value, null, null, body);
    }

    /**
     * Create a @code{thead} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void thead(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("thead", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{tbody} tag
     */
    public void tbody() {
        tag("tbody");
    }

    /**
     * Create en empty a @code{tbody} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void tbody(String attr, String value) {
        tag("tbody", attr, value);
    }

    /**
     * Create en empty a @code{tbody} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void tbody(String attr1, String value1, String attr2, String value2) {
        tag("tbody", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{tbody} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void tbody(Generator body) {
        tag("tbody", null, null, null, null, body);
    }

    /**
     * Create a @code{tbody} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void tbody(String attr, String value, Generator body) {
        tag("tbody", attr, value, null, null, body);
    }

    /**
     * Create a @code{tbody} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void tbody(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("tbody", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{tfoot} tag
     */
    public void tfoot() {
        tag("tfoot");
    }

    /**
     * Create en empty a @code{tfoot} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void tfoot(String attr, String value) {
        tag("tfoot", attr, value);
    }

    /**
     * Create en empty a @code{tfoot} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void tfoot(String attr1, String value1, String attr2, String value2) {
        tag("tfoot", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{tfoot} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void tfoot(Generator body) {
        tag("tfoot", null, null, null, null, body);
    }

    /**
     * Create a @code{tfoot} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void tfoot(String attr, String value, Generator body) {
        tag("tfoot", attr, value, null, null, body);
    }

    /**
     * Create a @code{tfoot} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void tfoot(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("tfoot", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{form} tag
     */
    public void form() {
        tag("form");
    }

    /**
     * Create en empty a @code{form} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void form(String attr, String value) {
        tag("form", attr, value);
    }

    /**
     * Create en empty a @code{form} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void form(String attr1, String value1, String attr2, String value2) {
        tag("form", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{form} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void form(Generator body) {
        tag("form", null, null, null, null, body);
    }

    /**
     * Create a @code{form} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void form(String attr, String value, Generator body) {
        tag("form", attr, value, null, null, body);
    }

    /**
     * Create a @code{form} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void form(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("form", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{input} tag
     */
    public void input() {
        tag("input");
    }

    /**
     * Create en empty a @code{input} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void input(String attr, String value) {
        tag("input", attr, value);
    }

    /**
     * Create en empty a @code{input} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void input(String attr1, String value1, String attr2, String value2) {
        tag("input", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{input} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void input(Generator body) {
        tag("input", null, null, null, null, body);
    }

    /**
     * Create a @code{input} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void input(String attr, String value, Generator body) {
        tag("input", attr, value, null, null, body);
    }

    /**
     * Create a @code{input} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void input(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("input", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{select} tag
     */
    public void select() {
        tag("select");
    }

    /**
     * Create en empty a @code{select} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void select(String attr, String value) {
        tag("select", attr, value);
    }

    /**
     * Create en empty a @code{select} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void select(String attr1, String value1, String attr2, String value2) {
        tag("select", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{select} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void select(Generator body) {
        tag("select", null, null, null, null, body);
    }

    /**
     * Create a @code{select} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void select(String attr, String value, Generator body) {
        tag("select", attr, value, null, null, body);
    }

    /**
     * Create a @code{select} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void select(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("select", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{option} tag
     */
    public void option() {
        tag("option");
    }

    /**
     * Create en empty a @code{option} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void option(String attr, String value) {
        tag("option", attr, value);
    }

    /**
     * Create en empty a @code{option} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void option(String attr1, String value1, String attr2, String value2) {
        tag("option", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{option} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void option(Generator body) {
        tag("option", null, null, null, null, body);
    }

    /**
     * Create a @code{option} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void option(String attr, String value, Generator body) {
        tag("option", attr, value, null, null, body);
    }

    /**
     * Create a @code{option} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void option(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("option", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{textarea} tag
     */
    public void textarea() {
        tag("textarea");
    }

    /**
     * Create en empty a @code{textarea} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void textarea(String attr, String value) {
        tag("textarea", attr, value);
    }

    /**
     * Create en empty a @code{textarea} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void textarea(String attr1, String value1, String attr2, String value2) {
        tag("textarea", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{textarea} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void textarea(Generator body) {
        tag("textarea", null, null, null, null, body);
    }

    /**
     * Create a @code{textarea} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void textarea(String attr, String value, Generator body) {
        tag("textarea", attr, value, null, null, body);
    }

    /**
     * Create a @code{textarea} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void textarea(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("textarea", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{button} tag
     */
    public void button() {
        tag("button");
    }

    /**
     * Create en empty a @code{button} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void button(String attr, String value) {
        tag("button", attr, value);
    }

    /**
     * Create en empty a @code{button} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void button(String attr1, String value1, String attr2, String value2) {
        tag("button", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{button} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void button(Generator body) {
        tag("button", null, null, null, null, body);
    }

    /**
     * Create a @code{button} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void button(String attr, String value, Generator body) {
        tag("button", attr, value, null, null, body);
    }

    /**
     * Create a @code{button} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void button(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("button", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{label} tag
     */
    public void label() {
        tag("label");
    }

    /**
     * Create en empty a @code{label} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void label(String attr, String value) {
        tag("label", attr, value);
    }

    /**
     * Create en empty a @code{label} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void label(String attr1, String value1, String attr2, String value2) {
        tag("label", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{label} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void label(Generator body) {
        tag("label", null, null, null, null, body);
    }

    /**
     * Create a @code{label} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void label(String attr, String value, Generator body) {
        tag("label", attr, value, null, null, body);
    }

    /**
     * Create a @code{label} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void label(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("label", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{p} tag
     */
    public void p() {
        tag("p");
    }

    /**
     * Create en empty a @code{p} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void p(String attr, String value) {
        tag("p", attr, value);
    }

    /**
     * Create en empty a @code{p} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void p(String attr1, String value1, String attr2, String value2) {
        tag("p", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{p} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void p(Generator body) {
        tag("p", null, null, null, null, body);
    }

    /**
     * Create a @code{p} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void p(String attr, String value, Generator body) {
        tag("p", attr, value, null, null, body);
    }

    /**
     * Create a @code{p} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void p(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("p", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{i} tag
     */
    public void i() {
        tag("i");
    }

    /**
     * Create en empty a @code{i} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void i(String attr, String value) {
        tag("i", attr, value);
    }

    /**
     * Create en empty a @code{i} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void i(String attr1, String value1, String attr2, String value2) {
        tag("i", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{i} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void i(Generator body) {
        tag("i", null, null, null, null, body);
    }

    /**
     * Create a @code{i} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void i(String attr, String value, Generator body) {
        tag("i", attr, value, null, null, body);
    }

    /**
     * Create a @code{i} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void i(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("i", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{a} tag
     */
    public void a() {
        tag("a");
    }

    /**
     * Create en empty a @code{a} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void a(String attr, String value) {
        tag("a", attr, value);
    }

    /**
     * Create en empty a @code{a} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void a(String attr1, String value1, String attr2, String value2) {
        tag("a", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{a} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void a(Generator body) {
        tag("a", null, null, null, null, body);
    }

    /**
     * Create a @code{a} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void a(String attr, String value, Generator body) {
        tag("a", attr, value, null, null, body);
    }

    /**
     * Create a @code{a} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void a(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("a", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{span} tag
     */
    public void span() {
        tag("span");
    }

    /**
     * Create en empty a @code{span} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void span(String attr, String value) {
        tag("span", attr, value);
    }

    /**
     * Create en empty a @code{span} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void span(String attr1, String value1, String attr2, String value2) {
        tag("span", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{span} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void span(Generator body) {
        tag("span", null, null, null, null, body);
    }

    /**
     * Create a @code{span} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void span(String attr, String value, Generator body) {
        tag("span", attr, value, null, null, body);
    }

    /**
     * Create a @code{span} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void span(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("span", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{img} tag
     */
    public void img() {
        tag("img");
    }

    /**
     * Create en empty a @code{img} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void img(String attr, String value) {
        tag("img", attr, value);
    }

    /**
     * Create en empty a @code{img} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void img(String attr1, String value1, String attr2, String value2) {
        tag("img", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{img} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void img(Generator body) {
        tag("img", null, null, null, null, body);
    }

    /**
     * Create a @code{img} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void img(String attr, String value, Generator body) {
        tag("img", attr, value, null, null, body);
    }

    /**
     * Create a @code{img} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void img(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("img", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{br} tag
     */
    public void br() {
        tag("br");
    }

    /**
     * Create en empty a @code{br} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void br(String attr, String value) {
        tag("br", attr, value);
    }

    /**
     * Create en empty a @code{br} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void br(String attr1, String value1, String attr2, String value2) {
        tag("br", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{br} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void br(Generator body) {
        tag("br", null, null, null, null, body);
    }

    /**
     * Create a @code{br} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void br(String attr, String value, Generator body) {
        tag("br", attr, value, null, null, body);
    }

    /**
     * Create a @code{br} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void br(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("br", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{small} tag
     */
    public void small() {
        tag("small");
    }

    /**
     * Create en empty a @code{small} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void small(String attr, String value) {
        tag("small", attr, value);
    }

    /**
     * Create en empty a @code{small} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void small(String attr1, String value1, String attr2, String value2) {
        tag("small", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{small} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void small(Generator body) {
        tag("small", null, null, null, null, body);
    }

    /**
     * Create a @code{small} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void small(String attr, String value, Generator body) {
        tag("small", attr, value, null, null, body);
    }

    /**
     * Create a @code{small} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void small(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("small", attr1, value1, attr2, value2, body);
    }

    /**
     * Create en empty a @code{strong} tag
     */
    public void strong() {
        tag("strong");
    }

    /**
     * Create en empty a @code{strong} tag
     * @param attr name of the attribute.
     * @param value value of the attribute.
     */
    public void strong(String attr, String value) {
        tag("strong", attr, value);
    }

    /**
     * Create en empty a @code{strong} tag
     * @param attr name1 of the attribute.
     * @param value value1 of the attribute.
     * @param attr name2 of the attribute.
     * @param value value2 of the attribute.
     */
    public void strong(String attr1, String value1, String attr2, String value2) {
        tag("strong", attr1, value1, attr2, value2);
    }

    /**
     * Create a @code{strong} tag with zero attribute
     * @param body the body generator for the tag.
     */
    public void strong(Generator body) {
        tag("strong", null, null, null, null, body);
    }

    /**
     * Create a @code{strong} tag with one attribute
     * @param attr name of the attribute.
     * @param value value of the attribute.
     * @param body the body generator for the tag.
     */
    public void strong(String attr, String value, Generator body) {
        tag("strong", attr, value, null, null, body);
    }

    /**
     * Create a @code{strong} tag with one attribute
     * @param attr1 name of the first attribute.
     * @param value1 value of the first attribute.
     * @param attr2 name of the second attribute.
     * @param value2 value of the second attribute.
     * @param body the body generator for the tag.
     */
    public void strong(String attr1, String value1, String attr2, String value2, Generator body) {
        tag("strong", attr1, value1, attr2, value2, body);
    }


}
